package com.aisqlanalyst.persistence;

/**
 * A single interaction row to be persisted into the Interactions_Table
 * (design "InteractionRepository" + Data Models, Change 10).
 *
 * <p>This record captures only the <em>writable</em> columns of an insert. The {@code id}
 * ({@code BIGSERIAL}) and {@code created_at} ({@code TIMESTAMPTZ NOT NULL DEFAULT now()}) columns
 * are generated by PostgreSQL at insert time, so they are intentionally absent here;
 * {@link InteractionRepository#save(Interaction)} does not supply them and lets the database
 * default {@code created_at} to {@code now()}.
 *
 * <p>Nullability mirrors the schema and the requirements:
 * <ul>
 *   <li>{@code question} and {@code status} map to {@code NOT NULL} columns and are always set.</li>
 *   <li>{@code generatedSql} is {@code null} when no SQL was generated for the interaction
 *       (e.g. the LLM failed before producing SQL) &mdash; matching the nullable
 *       {@code generated_sql} column (Requirements 6.1&ndash;6.4).</li>
 *   <li>{@code resultSummary} and {@code explanation} are nullable (e.g. a FAILED outcome may have
 *       no summary).</li>
 *   <li>{@code latencyMs} is a nullable {@link Long} mirroring the nullable {@code latency_ms BIGINT}
 *       column; it may be {@code null} when latency was not measured.</li>
 * </ul>
 *
 * @param question     the original natural-language question ({@code NOT NULL}).
 * @param generatedSql the SQL generated for this interaction, or {@code null} if none was produced.
 * @param resultSummary a short summary of the result, or {@code null}.
 * @param explanation  the natural-language explanation, or {@code null}.
 * @param status       the outcome, {@code SUCCESS} or {@code FAILED} ({@code NOT NULL}).
 * @param latencyMs    end-to-end latency in milliseconds, or {@code null} if not measured.
 */
public record Interaction(
        String question,
        String generatedSql,
        String resultSummary,
        String explanation,
        String status,
        Long latencyMs) {
}
